import { IconDefinition } from '@ant-design/icons-angular';
import {
  ArrowDownOutline,
  ArrowUpOutline,
  LockOutline,
  UserOutline,
  MailOutline,
  PoweroffOutline,
  BellOutline,
  MessageFill,
  ScheduleFill,
  FileFill,
  EllipsisOutline,
  SettingOutline,
  FullscreenOutline,
  FullscreenExitOutline,
  WeiboOutline,
  QqOutline,
  GoogleOutline,
  GithubOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  ContactsFill,
  BellFill,
  DeleteFill,
  SearchOutline,
  StopOutline,
  ClockCircleOutline,
  CloseCircleOutline,
  MessageOutline,
  CloseOutline,
  CheckCircleOutline,
  PhoneFill,
  EnvironmentFill,
  MailFill
} from '@ant-design/icons-angular/icons';

const icons: IconDefinition[] = [
  ArrowDownOutline,
  ArrowUpOutline,
  LockOutline,
  UserOutline,
  MailOutline,
  PoweroffOutline,
  BellOutline,
  MessageFill,
  ScheduleFill,
  FileFill,
  EllipsisOutline,
  SettingOutline,
  FullscreenOutline,
  FullscreenExitOutline,
  WeiboOutline,
  QqOutline,
  GoogleOutline,
  GithubOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  ContactsFill,
  BellFill,
  DeleteFill,
  SearchOutline,
  StopOutline,
  ClockCircleOutline,
  CloseCircleOutline,
  CheckCircleOutline,
  MessageOutline,
  CloseOutline,
  MailFill,
  PhoneFill,
  EnvironmentFill
];

export default icons;
